---
version: "2.0"

services:
  web:
    image: jjuarez/okteto-test:latest
    env_file: .env
    depends_on:
      - redis
    ports:
      - "8080:8080"
    links:
      - redis:redis
  redis:
    image: "redis:alpine"
